import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/shared/header/header";
import Footer from "@/components/shared/footer/footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const currentRoute = usePathname();

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className="min-h-[calc(100vh-100px)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
