import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Dashboard/Sidebar";

import Header from "@/components/shared/header/header";
import Footer from "@/components/shared/footer/footer";
import HeaderDashboard from "./(component)/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <HeaderDashboard />
        <div className="flex h-screen overflow-hidden">
          <div className='w-1/6 h-full hidden md:block'>
            <Sidebar />
          </div>
          <main className="flex-1 pt-16 overflow-x-hidden overflow-y-auto ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
